          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dino-park-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
            more_set_headers "X-Frame-Options: DENY" "X-XSS-Protection: 1" "X-Content-Type-Options: nosniff" "Strict-Transport-Security: max-age=63072000" "Content-Security-Policy: default-src 'self'; font-src https://fonts.gstatic.com; img-src 'self' data:; script-src 'self'; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'";
spec:
  rules:
  - host: dinopark-dev.allizom.community
    http:
      paths:
      - path: /api/v3
        backend:
          serviceName: dino-park-free-pass-service
          servicePort: 80
      - path: /
        backend:
          serviceName: dino-park-front-end-service
          servicePort: 80
