---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dino-park-ingress
  namespace: dino-park
spec:
  backend:
    serviceName: dino-park-front-end-service
    servicePort: 80
  rules:
  - host: dinopark.mozilla.community
    http:
      paths:
      - path: /beta
        backend:
          serviceName: dino-park-front-end-service
          servicePort: 80
      - path: /api/v3
        backend:
          serviceName: dino-park-free-pass-service
          servicePort: 80